{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sammati",
    "module": "sdk-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-0.2.0.aar",
          "url": "sdk-android-0.2.0.aar",
          "size": 133301,
          "sha512": "cb1957c098ac0fb623b6e89c1680b511034b9ad467356c1f00b09518a8d1d75c115b366929ef84b0aaa34858b8f5921e12315b0f0ad4506075415a19e69336a6",
          "sha256": "e56846642a98e5bb693c2b46c98fb97869d0de2c39c7049ddb51446de42aa629",
          "sha1": "b033a5cd90bb2c6cca3ca836f3769ef14d9ef473",
          "md5": "e9dd548a913271c717a0d199c6859c72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-0.2.0.aar",
          "url": "sdk-android-0.2.0.aar",
          "size": 133301,
          "sha512": "cb1957c098ac0fb623b6e89c1680b511034b9ad467356c1f00b09518a8d1d75c115b366929ef84b0aaa34858b8f5921e12315b0f0ad4506075415a19e69336a6",
          "sha256": "e56846642a98e5bb693c2b46c98fb97869d0de2c39c7049ddb51446de42aa629",
          "sha1": "b033a5cd90bb2c6cca3ca836f3769ef14d9ef473",
          "md5": "e9dd548a913271c717a0d199c6859c72"
        }
      ]
    }
  ]
}
