{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sammati",
    "module": "sdk-android",
    "version": "0.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-0.3.4.aar",
          "url": "sdk-android-0.3.4.aar",
          "size": 223434,
          "sha512": "11d06740cd294a138a0e4666b121c24eb24d4560678ce518f01f56e9770aedbe587f6d2093780122f0ca661813d7e6ba7ee0aba28be9ae27b3ce8ae333fae25a",
          "sha256": "b3dd366d7c65d8714528be57431cb94413489fe1bac5488dc68e73d8d31ae21f",
          "sha1": "f2035dc3ae2bc3cdb5b281072767828d6da19474",
          "md5": "2e0b6a632e4a3e51899ffd372893857d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-0.3.4.aar",
          "url": "sdk-android-0.3.4.aar",
          "size": 223434,
          "sha512": "11d06740cd294a138a0e4666b121c24eb24d4560678ce518f01f56e9770aedbe587f6d2093780122f0ca661813d7e6ba7ee0aba28be9ae27b3ce8ae333fae25a",
          "sha256": "b3dd366d7c65d8714528be57431cb94413489fe1bac5488dc68e73d8d31ae21f",
          "sha1": "f2035dc3ae2bc3cdb5b281072767828d6da19474",
          "md5": "2e0b6a632e4a3e51899ffd372893857d"
        }
      ]
    }
  ]
}
