#!/usr/bin/env bash
#
# Builds the public SDK artifacts from the private Sammati monorepo into this
# publisher repo. Source stays private; only built artifacts land here.
#
#   MONO=/path/to/synapsedatalabs ./scripts/build-artifacts.sh
#
# Produces:
#   npm/*.tgz                       — JS packages (RN, Capacitor, Node)
#   cocoapods/Sammati.podspec       — iOS SDK podspec (http source)
#   cocoapods/sources/*.zip         — iOS SDK source zip the podspec points at
#   maven/                          — Android Maven repo (populated by gradle; see scripts/publish-android.sh)
#
set -euo pipefail

MONO="${MONO:-/Users/vinod/myprojects/synapsedatalabs}"
DIST="$(cd "$(dirname "$0")/.." && pwd)"
OWNER_REPO="sammatiind/sammati-sdks"
RAW="https://raw.githubusercontent.com/${OWNER_REPO}/main"

echo "MONO = $MONO"
echo "DIST = $DIST"

# ---------------------------------------------------------------- JS (npm)
echo "==> Packing JS packages"
mkdir -p "$DIST/npm"
rm -f "$DIST/npm"/*.tgz
for p in sdk-react-native sdk-capacitor sdk-node; do
  npm pack "$MONO/packages/$p" --pack-destination "$DIST/npm" >/dev/null
  echo "    packed $p"
done

# ---------------------------------------------------------------- iOS (CocoaPods)
echo "==> Building iOS source zip + podspec"
IOS_VER="$(grep -E "s\.version" "$MONO/packages/sdk-ios/Sammati.podspec" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | head -1)"
mkdir -p "$DIST/cocoapods/sources"
ZIP="$DIST/cocoapods/sources/sammati-ios-${IOS_VER}.zip"
rm -f "$ZIP"
( cd "$MONO/packages/sdk-ios" && zip -rq "$ZIP" Sources Package.swift README.md )
echo "    zipped iOS source -> $(basename "$ZIP")"

cat > "$DIST/cocoapods/Sammati.podspec" <<EOF
# Generated by scripts/build-artifacts.sh — do not edit by hand.
# Public CocoaPods manifest for the Sammati iOS SDK. Source is an http zip
# hosted in this publisher repo (the private monorepo is never exposed).
Pod::Spec.new do |s|
  s.name             = 'Sammati'
  s.version          = '${IOS_VER}'
  s.summary          = 'DPDP Act 2023 consent SDK for iOS apps.'
  s.homepage         = 'https://sammati.io'
  s.license          = { :type => 'Apache-2.0' }
  s.author           = { 'Sammati' => 'support@sammati.io' }
  s.source           = { :http => '${RAW}/cocoapods/sources/sammati-ios-${IOS_VER}.zip' }
  s.ios.deployment_target = '14.0'
  s.swift_versions   = ['5.7', '5.8', '5.9', '5.10']
  s.source_files     = 'Sources/Sammati/**/*.swift'
  s.frameworks       = 'Foundation', 'Security', 'UIKit', 'SwiftUI', 'SafariServices'
end
EOF
echo "    wrote cocoapods/Sammati.podspec (v${IOS_VER})"

# ---------------------------------------------------------------- Android (Maven)
echo "==> Android: requires a JDK + Gradle (not built here)."
echo "    Run scripts/publish-android.sh on a machine with the Android toolchain."
mkdir -p "$DIST/maven"
touch "$DIST/maven/.gitkeep"

echo "==> Done. Artifacts under $DIST"
